### ISSUE TITLE
Error During Indexing

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/terrier-docker#28]
When running `python3 run.py prepare --repo osirrc2019/terrier --collections robust04=/home/jig/collections/disk45=trectext`, I get the following error near the end of indexing:

```
20:01:52.404 [main] INFO  o.t.s.indexing.LexiconBuilder - Optimising structure lexicon
20:01:52.405 [main] INFO  o.t.s.i.FSOMapFileLexiconUtilities - Optimising lexicon with 63468 entries
20:01:52.416 [ForkJoinPool.commonPool-worker-19] INFO  o.t.structures.CompressingMetaIndex - Structure meta reading lookup file into memory
20:01:52.417 [ForkJoinPool.commonPool-worker-19] INFO  o.t.structures.CompressingMetaIndex - Structure meta loading data file into memory
20:01:52.427 [ForkJoinPool.commonPool-worker-57] INFO  o.t.s.indexing.LexiconBuilder - Optimising structure lexicon
20:01:52.428 [ForkJoinPool.commonPool-worker-57] INFO  o.t.s.i.FSOMapFileLexiconUtilities - Optimising lexicon with 54357 entries
20:01:52.428 [main] INFO  o.t.structures.indexing.Indexer - Finished building the inverted index...
20:01:52.428 [main] INFO  o.t.structures.indexing.Indexer - Time elapsed for inverted file: 8
20:01:52.434 [ForkJoinPool.commonPool-worker-15] INFO  o.t.structures.CompressingMetaIndex - Structure meta reading lookup file into memory
20:01:52.434 [main] ERROR o.t.a.ThreadedBatchIndexing - Problem occurred during parallel indexing
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006) ~[na:1.8.0_212]
        at org.terrier.applications.ThreadedBatchIndexing.index(ThreadedBatchIndexing.java:166) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:114) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.CLITool.main(CLITool.java:316) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
Caused by: java.lang.NullPointerException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_212]
Total time elaped: 348 seconds
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479) ~[na:1.8.0_212]
        at org.terrier.applications.ThreadedBatchIndexing.lambda$0(ThreadedBatchIndexing.java:166) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.externalInterruptibleAwaitDone(ForkJoinTask.java:361) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1001) ~[na:1.8.0_212]
        ... 4 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.terrier.structures.merging.StructureMerger.mergeStructures(StructureMerger.java:681) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.ThreadedBatchIndexing$2.apply(ThreadedBatchIndexing.java:147) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.ThreadedBatchIndexing$2.apply(ThreadedBatchIndexing.java:1) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$2ReducingSink.combine(ReduceOps.java:135) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$2ReducingSink.combine(ReduceOps.java:107) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$ReduceTask.onCompletion(ReduceOps.java:754) ~[na:1.8.0_212]
        at java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:577) ~[na:1.8.0_212]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:317) ~[na:1.8.0_212]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_212]
20:01:52.434 [ForkJoinPool.commonPool-worker-15] INFO  o.t.structures.CompressingMetaIndex - Structure meta loading data file into memory
Setting TERRIER_HOME to /work/terrier-core
Index not found at /work/indexes/,robust04
Indexing...
{}
Indexing command is 
        /work/terrier-core/bin/terrier batchindexing -p
        -I /work/indexes/robust04 -Dterrier.mvn.coords=org.apache.commons:commons-compress:1.18 -Dfiles.mappings=Z:org.apache.commons.compress.compressors.z.ZCompressorInputStream:null,z:org.apache.commons.compress.compressors.z.ZCompressorInputStream:null -DTrecDocTags.process=TEXT,H3,DOCTITLE,HEADLINE,TTL 
Committing image...
```
Are you able to take a look @ArthurCamara or @cmacdonald?

**Comment by cmacdonald** [comment]
Havent seen this one before, and can't see from the code why it would happen. Think my Docker host only supplies one CPU, hence why I hadn't observed it.

@r-clancy : if you remove the `-p` flag in /index, you should be good to go.

Craig

**Comment by ryan-clancy** [comment]
Removing the `-p` flag seems to do the trick - thanks!

**Comment by cmacdonald** [comment]
@r-clancy was there any earlier exceptions in the indexing log when `-p` is used? I find it difficult to see how the exception above could have occurred.

**Comment by ryan-clancy** [comment]
Here is the log, no obvious exceptions appear: [terrier.log](https://github.com/osirrc/terrier-docker/files/3272774/terrier.log)

**Comment by cmacdonald** [comment]
Thanks, I will investigate.

Craig

**Comment by cmacdonald** [comment]
It seems that the FR has .0z .1z .2z files. I am patching /index to be able to read them also.  I will have to request an original copy of the TREC disks (ours are gzipped).

**Comment by cmacdonald** [comment]
should be fixed now.

**Comment by ryan-clancy** [comment]
This issue seems to be fixed, but it still seems to index the duplicate document - tracking in https://github.com/osirrc/terrier-docker/issues/29.
