### ISSUE TITLE
ClassNotFoundException for DFRD Run

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/terrier-docker#37]
When doing the official run through, I get the following error on the DFRD run (everything else seems fine).

Prepare command: `python run.py prepare --repo osirrc2019/terrier --tag v0.1.5 --collections [COLLECTION_NAME]=[COLLECTION_PATH]=[COLLECTION_FORMAT] --opts block.index=true`
Search command: `python run.py search --repo osirrc2019/terrier --tag v0.1.5 --output [OUTPUT]/terrier --qrels [QRELS_PATH] --topic [TOPIC_PATH] --collection [COLLECTION_NAME] --timings --opts config=DFRD`

```
06:37:35.058 [main] ERROR org.terrier.matching.Matching - Exception while initialising default modifiers. Please check the name of the modifiers in the configuration file.
java.lang.ClassNotFoundException: org.terrier.matching.dsms.true
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_212]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_212]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_212]
	at org.terrier.utility.ApplicationSetup.getClass(ApplicationSetup.java:405) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.matching.BaseMatching.<init>(BaseMatching.java:167) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.matching.daat.Full.<init>(Full.java:64) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_212]
	at org.terrier.querying.LocalManager$ApplyLocalMatching.getMatchingModel(LocalManager.java:398) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.querying.LocalManager$ApplyLocalMatching.process(LocalManager.java:447) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.querying.LocalManager.runSearchRequest(LocalManager.java:845) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.batchquerying.TRECQuerying.processQuery(TRECQuerying.java:720) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.batchquerying.TRECQuerying.processQueryAndWrite(TRECQuerying.java:631) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:830) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.batchquerying.TRECQuerying.processQueries(TRECQuerying.java:743) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.batchquerying.TRECQuerying$Command.run(TRECQuerying.java:257) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.AbstractQuerying$AbstractQueryingCommand.run(AbstractQuerying.java:160) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.terrier.applications.CLITool.main(CLITool.java:316) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
```

Log file here: https://drive.google.com/file/d/1u_P9O2_WkwEVrY7nJWttVWcGta4MrAoH/view?usp=drivesdk

Looks like a JAR might be missing?

**Comment by ArthurCamara** [comment]
I believe this was just a documentation problem. there is no `DFRD` configuration. It's an  "add-on" config (like query expansion). I'm updating the docs now.

**Comment by ArthurCamara** [comment]
1812f7407f917b5b6093b5c84a9b54399103bbd9 should clarify this

**Comment by ArthurCamara** [comment]
Can you give it a shot with https://github.com/osirrc/terrier-docker/tree/v0.1.6 ?

**Comment by cmacdonald** [comment]
I think we should avoid "DRFD", as it doesnt correspond to an actual weighting model. Its any given weighting model plus proximity.

**Comment by ArthurCamara** [comment]
> I think we should avoid "DRFD", as it doesnt correspond to an actual weighting model. Its any given weighting model plus proximity.

Yup. I've updated the Readme to clarify that.

**Comment by ryan-clancy** [comment]
I'll remove DFRD from the official runs - thanks!
