### ISSUE TITLE
Error During core18 Indexing

### ISSUE THREAD

**Issue by ryan-clancy** [osirrc/terrier-docker#38]
When doing the `core18` run, I get errors during indexing:

```
19:39:16.091 [main] ERROR o.t.a.ThreadedBatchIndexing - Problem occurred during parallel indexing
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: This is not a JSON Object.
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006) ~[na:1.8.0_212]
        at org.terrier.applications.ThreadedBatchIndexing.index(ThreadedBatchIndexing.java:186) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.BatchIndexing$Command.run(BatchIndexing.java:114) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.CLITool.main(CLITool.java:316) [terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: This is not a JSON Object.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_212]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479) ~[na:1.8.0_212]
        at org.terrier.applications.ThreadedBatchIndexing.lambda$index$1(ThreadedBatchIndexing.java:186) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.externalInterruptibleAwaitDone(ForkJoinTask.java:361) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1001) ~[na:1.8.0_212]
        ... 4 common frames omitted
Caused by: java.lang.IllegalStateException: This is not a JSON Object.
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:83) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.indexing.TwitterJSONCollection.readTweet(TwitterJSONCollection.java:241) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at uk.ac.gla.terrier.indexing.WAPOCollection.nextDocument(WAPOCollection.java:118) ~[terrier-wapo-0.1.jar:na]
        at org.terrier.structures.indexing.classical.BasicIndexer.createDirectIndex(BasicIndexer.java:241) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.structures.indexing.Indexer.index(Indexer.java:346) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.TRECIndexing.index(TRECIndexing.java:154) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.ThreadedBatchIndexing$1.apply(ThreadedBatchIndexing.java:131) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.terrier.applications.ThreadedBatchIndexing$1.apply(ThreadedBatchIndexing.java:122) ~[terrier-project-5.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_212]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_212]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[na:1.8.0_212]
        at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[na:1.8.0_212]
        at java.util.stream.AbstractTask.compute(AbstractTask.java:316) ~[na:1.8.0_212]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_212]
```

Indexing is run as `python run.py prepare --repo osirrc2019/terrier --tag v0.1.5 --collections core18=/home/jig/collections/WashingtonPost.v2/=json`

Any ideas?

Full logs: https://drive.google.com/file/d/111PhdW4nGomhmYiCL8mh_9JVsdCLMH6Q/view?usp=drivesdk

**Comment by ArthurCamara** [comment]
Seems like the problem is coming when running the `index` script with `--opts=block.index=true`.
I'm investigating that now

**Comment by ArthurCamara** [comment]
I couldn't reproduce the problem... `python run.py prepare --repo osirrc2019/terrier --tag v0.1.6 --collections core18=/ssd2/claudia/WashingtonPost.v2/data/=json --opts=block.index=true` ran smoothly

**Comment by ArthurCamara** [comment]
@cmacdonald Can you take a look at this?

**Comment by cmacdonald** [comment]
Thanks for the headsup chaps.

Checking the logs, I see that its indexing `/input/collections/core18/scripts/wapo-print-docids.py`

We need to agree the mountpoint for the WAPO collection. Is it the root folder, or the data folder. If the former, we would need to grep out the collection.spec manually etc.

**Comment by ArthurCamara** [comment]
9fc9f990a7afb66540b213ce11d2c50c42967753 should fix it.
Can you check it @r-clancy ?

**Comment by ryan-clancy** [comment]
The WaPo collection is mounted at its root directory, see https://github.com/osirrc/jig/blob/master/collections/core18.tree

Will test and report back.

**Comment by ryan-clancy** [comment]
It looks to work on the latest commit, but not on the `v0.1.6` tag - can you cut a `v0.1.7` with the latest commit so I can use that for the runs?

**Comment by ArthurCamara** [comment]
There you go: https://github.com/osirrc/terrier-docker/releases/tag/v0.1.7

**Comment by ryan-clancy** [comment]
Thanks! I'll close this issue once I do the run...
